[project]
name = "chat-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=1.2.0",
    "openai>=1.50.1",
    "python-dotenv>=1.0.1",
    "toml>=0.10.2",
]
