name: LLMER-BPD-Actions (Test Branch)

on:
  push:
    branches:
      - test

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: tags
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="test"
          UNIQUE_TAG="${TIMESTAMP}-${SHORT_SHA}-test"
          echo "DOCKER_HUB_TAG=${{ secrets.DOCKER_IMAGE_NAME }}/llmer:${IMAGE_TAG}" >> $GITHUB_ENV
          echo "DOCKER_HUB_UNIQUE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}/llmer:${UNIQUE_TAG}" >> $GITHUB_ENV

      - name: Build and publish image
        run: |
          docker buildx build \
            -f Dockerfile \
            --platform linux/amd64 \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=LLmer image" \
            --push \
            --tag ${{ env.DOCKER_HUB_TAG }} \
            --tag ${{ env.DOCKER_HUB_UNIQUE_TAG }} \
            .

      - name: Deploy to test server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ secrets.TEST_PORT }}
          username: ${{ secrets.TEST_SSH_USER }}
          key: ${{ secrets.TEST_ID_RSA }}
          script: |
            compose-operation -p ${{ secrets.TEST_DEPLOY_PATH }}
